static char * device_table[SND_DEVICE_MAX] = {
		<device name="SND_DEVICE_NONE" alias=""/>
		<device name="SND_DEVICE_OUT_HANDSET" alias="handset"/>
		<device name="SND_DEVICE_OUT_SPEAKER" alias="speaker"/>
		<device name="SND_DEVICE_OUT_SPEAKER_STEREO" alias="speaker-stereo"/>
		<device name="SND_DEVICE_OUT_SPEAKER_EXTERNAL_1" alias="speaker-ext-1"/>
		<device name="SND_DEVICE_OUT_SPEAKER_EXTERNAL_2" alias="speaker-ext-2"/>
		<device name="SND_DEVICE_OUT_SPEAKER_VBAT" alias="speaker-reverse"/>
		<device name="SND_DEVICE_OUT_SPEAKER_REVERSE" alias="speaker-vbat"/>
		<device name="SND_DEVICE_OUT_HEADPHONES" alias="line"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_24BIT_44P1K" alias="headphones"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_24BIT_48K" alias="headphones-hifi-24bit-44P1KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_24BIT_96K" alias="headphones-hifi-24bit-48KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_24BIT_192K" alias="headphones-hifi-24bit-96KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_16BIT_44P1K" alias="headphones-hifi-24bit-192KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_16BIT_48K" alias="headphones-hifi-16bit-44P1KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_16BIT_96K" alias="headphones-hifi-16bit-48KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_16BIT_192K" alias="headphones-hifi-16bit-96KHZ"/>
		<device name="SND_DEVICE_OUT_HEADPHONES_44_1" alias="headphones-hifi-16bit-192KHZ"/>
		<device name="SND_DEVICE_OUT_LINE" alias="headphones-44.1"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_HEADPHONES" alias="speaker-and-headphones"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_LINE" alias="speaker-and-line"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_HEADPHONES_EXTERNAL_1" alias="speaker-and-headphones-ext-1"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_HEADPHONES_EXTERNAL_2" alias="speaker-and-headphones-ext-2"/>
		<device name="SND_DEVICE_OUT_VOICE_HANDSET" alias="voice-handset"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER" alias="voice-speaker"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_NB" alias="voice-speaker-nb"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_WB" alias="voice-speaker-wb"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_STEREO" alias="voice-speaker-stereo"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_STEREO_NB" alias="voice-speaker-stereo-nb"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_STEREO_WB" alias="voice-speaker-stereo-wb"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_BRIGHTNESS" alias="voice-speaker-brightness"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_STEREO_BRIGHTNESS" alias="voice-speaker-stereo-brightness"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_VBAT" alias="voice-speaker-vbat"/>
		<device name="SND_DEVICE_OUT_VOICE_HEADPHONES" alias="voice-headphones"/>
		<device name="SND_DEVICE_OUT_VOICE_LINE" alias="voice-line"/>
		<device name="SND_DEVICE_OUT_HDMI" alias="hdmi"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_HDMI" alias="speaker-and-hdmi"/>
		<device name="SND_DEVICE_OUT_BT_SCO" alias="bt-sco-headset"/>
		<device name="SND_DEVICE_OUT_BT_SCO_WB" alias="bt-sco-headset-wb"/>
		<device name="SND_DEVICE_OUT_VOICE_TTY_FULL_HEADPHONES" alias="voice-tty-full-headphones"/>
		<device name="SND_DEVICE_OUT_VOICE_TTY_VCO_HEADPHONES" alias="voice-tty-vco-headphones"/>
		<device name="SND_DEVICE_OUT_VOICE_TTY_HCO_HANDSET" alias="voice-tty-hco-handset"/>
		<device name="SND_DEVICE_OUT_AFE_PROXY" alias="afe-proxy"/>
		<device name="SND_DEVICE_OUT_USB_HEADSET" alias="usb-headphones"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_USB_HEADSET" alias="speaker-and-usb-headphones"/>
		<device name="SND_DEVICE_OUT_TRANSMISSION_FM" alias="transmission-fm"/>
		<device name="SND_DEVICE_OUT_ANC_HEADSET" alias="anc-headphones"/>
		<device name="SND_DEVICE_OUT_ANC_FB_HEADSET" alias="anc-fb-headphones"/>
		<device name="SND_DEVICE_OUT_VOICE_ANC_HEADSET" alias="voice-anc-headphones"/>
		<device name="SND_DEVICE_OUT_VOICE_ANC_FB_HEADSET" alias="voice-anc-fb-headphones"/>
		<device name="SND_DEVICE_OUT_SPEAKER_AND_ANC_HEADSET" alias="speaker-and-anc-headphones"/>
		<device name="SND_DEVICE_OUT_ANC_HANDSET" alias="anc-handset"/>
		<device name="SND_DEVICE_OUT_HAC_HANDSET" alias="hac-handset"/>
		<device name="SND_DEVICE_OUT_ANC_HANDSET_BRIGHTNESS" alias="anc-handset-brightness"/>
		<device name="SND_DEVICE_OUT_SPEAKER_PROTECTED" alias="speaker-protected"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_PROTECTED" alias="voice-speaker-protected"/>
		<device name="SND_DEVICE_OUT_SPEAKER_PROTECTED_VBAT" alias="speaker-protected-vbat"/>
		<device name="SND_DEVICE_OUT_VOICE_SPEAKER_PROTECTED_VBAT" alias="voice-speaker-protected-vbat"/>
		<device name="SND_DEVICE_IN_HANDSET_MIC" alias="handset-mic"/>
		<device name="SND_DEVICE_IN_HANDSET_MIC_EXTERNAL" alias="handset-mic-ext"/>
		<device name="SND_DEVICE_IN_HANDSET_MIC_AEC" alias="handset-mic"/>
		<device name="SND_DEVICE_IN_HANDSET_MIC_NS" alias="handset-mic"/>
		<device name="SND_DEVICE_IN_HANDSET_MIC_AEC_NS" alias="handset-mic"/>
		<device name="SND_DEVICE_IN_HANDSET_DMIC" alias="dmic-endfire"/>
		<device name="SND_DEVICE_IN_HANDSET_DMIC_AEC" alias="dmic-endfire"/>
		<device name="SND_DEVICE_IN_HANDSET_DMIC_NS" alias="dmic-endfire"/>
		<device name="SND_DEVICE_IN_HANDSET_DMIC_AEC_NS" alias="dmic-endfire"/>
		<device name="SND_DEVICE_IN_SPEAKER_MIC" alias="speaker-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_MIC_AEC" alias="speaker-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_MIC_NS" alias="speaker-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_MIC_AEC_NS" alias="speaker-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_STEREO_MIC" alias="speaker-stereo-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC" alias="speaker-dmic-endfire"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_AEC" alias="speaker-dmic-endfire"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_NS" alias="speaker-dmic-endfire"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_AEC_NS" alias="speaker-dmic-endfire"/>
		<device name="SND_DEVICE_IN_HEADSET_MIC" alias="headset-mic"/>
		<device name="SND_DEVICE_IN_HEADSET_BACKMIC" alias="headset-backmic"/>
		<device name="SND_DEVICE_IN_HEADSET_MIC_FLUENCE" alias="headset-mic"/>
		<device name="SND_DEVICE_IN_HEADSET_BACKMIC_FLUENCE" alias="headset-backmic"/>
		<device name="SND_DEVICE_IN_VOICE_SPEAKER_MIC" alias="voice-speaker-mic"/>
		<device name="SND_DEVICE_IN_VOICE_SPEAKER_STEREO_MIC" alias="voice-speaker-stereo-mic"/>
		<device name="SND_DEVICE_IN_VOICE_HEADSET_MIC" alias="voice-headset-mic"/>
		<device name="SND_DEVICE_IN_VOICE_HEADSET_BACKMIC" alias="voice-headset-backmic"/>
		<device name="SND_DEVICE_IN_HDMI_MIC" alias="hdmi-mic"/>
		<device name="SND_DEVICE_IN_BT_SCO_MIC" alias="bt-sco-mic"/>
		<device name="SND_DEVICE_IN_BT_SCO_MIC_NREC" alias="bt-sco-mic"/>
		<device name="SND_DEVICE_IN_BT_SCO_MIC_WB" alias="bt-sco-mic-wb"/>
		<device name="SND_DEVICE_IN_BT_SCO_MIC_WB_NREC" alias="bt-sco-mic-wb"/>
		<device name="SND_DEVICE_IN_CAMCORDER_MIC" alias="camcorder-mic"/>
		<device name="SND_DEVICE_IN_VOICE_DMIC" alias="voice-dmic-ef"/>
		<device name="SND_DEVICE_IN_VOICE_SPEAKER_DMIC" alias="voice-speaker-dmic-ef"/>
		<device name="SND_DEVICE_IN_VOICE_SPEAKER_QMIC" alias="voice-speaker-qmic"/>
		<device name="SND_DEVICE_IN_VOICE_TTY_FULL_HEADSET_MIC" alias="voice-tty-full-headset-mic"/>
		<device name="SND_DEVICE_IN_VOICE_TTY_VCO_HANDSET_MIC" alias="voice-tty-vco-handset-mic"/>
		<device name="SND_DEVICE_IN_VOICE_TTY_HCO_HEADSET_MIC" alias="voice-tty-hco-headset-mic"/>
		<device name="SND_DEVICE_IN_VOICE_REC_MIC" alias="voice-rec-mic"/>
		<device name="SND_DEVICE_IN_AUDIO_REC_MIC" alias="audio-rec-mic"/>
		<device name="SND_DEVICE_IN_VOICE_REC_MIC_NS" alias="voice-rec-mic"/>
		<device name="SND_DEVICE_IN_VOICE_REC_DMIC_STEREO" alias="voice-rec-dmic-ef"/>
		<device name="SND_DEVICE_IN_VOICE_REC_DMIC_FLUENCE" alias="voice-rec-dmic-ef-fluence"/>
		<device name="SND_DEVICE_IN_USB_HEADSET_MIC" alias="usb-headset-mic"/>
		<device name="SND_DEVICE_IN_CAPTURE_FM" alias="capture-fm"/>
		<device name="SND_DEVICE_IN_AANC_HANDSET_MIC" alias="aanc-handset-mic"/>
		<device name="SND_DEVICE_IN_QUAD_MIC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_HANDSET_STEREO_DMIC" alias="handset-stereo-dmic-ef"/>
		<device name="SND_DEVICE_IN_SPEAKER_STEREO_DMIC" alias="speaker-stereo-dmic-ef"/>
		<device name="SND_DEVICE_IN_CAPTURE_VI_FEEDBACK" alias="vi-feedback"/>
		<device name="SND_DEVICE_IN_VOICE_SPEAKER_DMIC_BROADSIDE" alias="voice-speaker-dmic-broadside"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_BROADSIDE" alias="speaker-dmic-broadside"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_AEC_BROADSIDE" alias="speaker-dmic-broadside"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_NS_BROADSIDE" alias="speaker-dmic-broadside"/>
		<device name="SND_DEVICE_IN_SPEAKER_DMIC_AEC_NS_BROADSIDE" alias="speaker-dmic-broadside"/>
		<device name="SND_DEVICE_IN_HANDSET_QMIC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_QMIC_AEC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_QMIC_NS" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_SPEAKER_QMIC_AEC_NS" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_TEST_MAIN_MIC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_TEST_RECEIVER_MIC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_TEST_BACK_MIC" alias="quad-mic"/>
		<device name="SND_DEVICE_IN_QUAD_FLUENCE_MIC" alias="quad-fluence-mic"/>
};
